name: pull-auto-merge
on: pull_request

permissions:
  contents: write

jobs:
  pull-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'pull[bot]'
    steps:
      - name: Enable auto-merge for pull[bot] prs
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
